- README.md
- queries/rust/textobjects.scm
Fix https://github.com/nvim-treesitter/nvim-treesitter/issues/544
> Add @parameter.inner for Rust

- README.md
- queries/lua/textobjects.scm
- Fix install instructions
- Add more lua textobjects definitions
> Add more Lua textobjs

- lua/nvim-treesitter/textobjects/move.lua
- lua/nvim-treesitter/textobjects/shared.lua
@stsewd is this how the movement should behave? I am tired, it's almost weekend... So this is just a quick guess...
Fix nvim-treesitter/nvim-treesitter#343
> Make move behave like vim move commands

- queries/lua/textobjects.scm
Set function's parameters as parameters text-objects
> feat: Add more lua text-objects

- queries/dart/textobjects.scm
Hi, here is my try to add text-object imp for `dart`.
Would very much appreciate any feedback.
**problem with sequence**
Is it just me but sequence with multiple nodes does not work - only last count:
```
(
(method_signature)
(function_body)
) @function.outer
```
Thanks
P.S.: I am new to tree-sitter family and open-source contributing.
> Add dart textobjects.scm

- queries/dart/textobjects.scm
> Dart: add function.outer

- queries/javascript/textobjects.scm
- queries/typescript/textobjects.scm
Wanna do some swap with js and ts :)
> Add @parameter.inner for js and ts

- README.md
- queries/bash/textobjects.scm
Add missing bash textobjects queries
> feat: Add bash textobjects

- queries/java/textobjects.scm
Probably not complete, but good enough for me.
> feat: add queries for java

- queries/html/textobjects.scm
Same as rst, classes are titles and the rest are functions.
We could also add attributes as paramenters, but I can add that in
another PR.
> HTML: add textobjects

- queries/rst/textobjects.scm
Ref https://github.com/neovim/neovim/pull/14039#issuecomment-791621565
> rst: update textobjects

- queries/julia/textobjects.scm
Add some basic text-object queries for Julia.
> Add first Julia queries

- .github/workflows/update-readme.yml
- .luacheckrc
- README.md
- lua/nvim-treesitter/textobjects/shared.lua
Depends on https://github.com/nvim-treesitter/nvim-treesitter/pull/1105
> Add support for injected languages

- queries/java/textobjects.scm
> Hotfix: update Java textobjects

- queries/julia/textobjects.scm
* Update queries for `@parameter_outer` in:
- call_expression / argument_list
- function_definition / parameter_list
* Add queries for:
- structs
- math functions
- macros
> Update Julia queries

- README.md
- queries/ruby/textobjects.scm
This PR adds Ruby support for the following:
```
@function.outer
@class.outer
@condition.outer
@loop.outer
@call.outer
@block.outer
```
> Add Ruby textobjects

- lua/nvim-treesitter/textobjects/attach.lua
Not all modules that use this function define keymaps
> Fix error on detach for modules without keymaps

- README.md
- doc/nvim-treesitter-textobjects.txt
- lua/nvim-treesitter-textobjects.lua
- lua/nvim-treesitter/textobjects/lsp_interop.lua
Just a small addition to optionally enable border for peek definition popup
> Add border option for lsp_interop popup

- README.md
- doc/nvim-treesitter-textobjects.txt
- lua/nvim-treesitter-textobjects.lua
- lua/nvim-treesitter/textobjects/lsp_interop.lua
Apologies about the snafu with linting and multi commits.
This should fix it
> Fix lsp_interop linting

- README.md
There's a comma missing. Thats all ;)
> Fix missing comma in README

- queries/c_sharp/textobjects.scm
Adds the basic captures for loops, conditionals and classes.
> Adds more C# captures

- queries/zig/textobjects.scm
Adds a basic implementation of the Zig textobjects. Might not implement more advanced constructs.
> Adds zig textobjects

- queries/zig/textobjects.scm
- I updated, and tested with the new parser on my machine
- I don't know the proper way to use the textobject query. Should i separate them in multiple query. Example
```
(_
(IfPrefix) @conditional.inner
(_) @conditional.inner
(ElseTail)? @conditional.inner) @conditional.outer
```
> Update zig textobjects

- queries/elixir/textobjects.scm
There may be some incompatible parts.  😅 
- function: with/without condition, do block/inline, anonymous_function
- class: actually it is module
- comment: heredoc docs only
- block
> Add Elixir textobjects

- lua/nvim-treesitter/textobjects/lsp_interop.lua
After this [PR](https://github.com/neovim/neovim/pull/15504) is merged, I can't use `peek_definition_code`.
So this PR to check and use a correct callback.
> Update new signature handler

- queries/fennel/textobjects.scm
First time doing Treesitter queries, please be gentle. :D
Couldn't get `#offset!` working for `@parameter.outer`, not sure what's up. I left them there anyways as they don't seem to cause any issues either.
Fennel doesn't have statements, but I defined `@statement.outer` to be anything surrounded by parenthesis. I found it useful for at least selecting, moving, and swapping.
> Fennel textobjects

- queries/scala/textobjects.scm
Not a complete set of bindings for scala, but a good start.
> Add simple bindings for scala

- queries/go/textobjects.scm
Fix https://github.com/nvim-treesitter/nvim-treesitter/issues/2200
> Fix go textobj

- doc/nvim-treesitter-textobjects.txt
> chore(docs): update per-language instructions

- queries/latex/textobjects.scm
see https://github.com/nvim-treesitter/nvim-treesitter/pull/2436
@seblj
> chore(latex): adapt to parser changes

- queries/supercollider/textobjects.scm
This is a first of still to come textobject queries for [supercollider](https://github.com/madskjeldgaard/tree-sitter-supercollider)
> textobjects for supercollider

- queries/r/textobjects.scm
> r: update nodes

- queries/julia/textobjects.scm
See tree-sitter/tree-sitter-julia#31
> Update julia comments

- .github/workflows/check_query_files.yml
- queries/dart/textobjects.scm
Tests for Dart were failing this night due to this.
Ref: https://github.com/UserNobody14/tree-sitter-dart/commit/5e5d9533b52a14d6b324fdaa6061ca0af519f896
> fix(dart): labeled_statement was out-commented

- CONTRIBUTING.md
- queries/html/textobjects.scm
`daa` - delete around attribute (i.e. delete entire attribute)
`cia` - change inner attribute (i.e. attr value)
> feat(html): add `@attribute.inner`, `outer`

- queries/markdown/textobjects.scm
> fix(markdown): update markdown ts query for breaking parser change

- lua/nvim-treesitter/textobjects/lsp_interop.lua
> Stylua update

- queries/hack/textobjects.scm
Will add support for @function.inner, @class.outer, @class.inner in a subsquent diff
> Add support for hack lang @function.outer

- README.md
- lua/nvim-treesitter-textobjects.lua
- lua/nvim-treesitter/textobjects/select.lua
To me this feels like what should be the default behaviour but not sure if this should be configurable or not?
> makes function and class objects linewise

- queries/elixir/textobjects.scm
> Add additional Elixir query to correctly handle shorthand function declarations

- lua/nvim-treesitter/textobjects/select.lua
fixes to issues:
1. There was a bug when for example a function was on the last line of the buffer and we tried to get text outside of the buffer which is now fixed.
2. As discussed in #235 there was an issue when both linewise mode and include selection was used. This is because in charwise mode we include the newline of the last previous line in order to remove the correct number of newlines. But if the visual mode is linewise this deletes the whole previous line. This fixes this by moving one character forward in the case of linewise.
> fix(select): fix whitespace inclusion for linewise mode

- queries/javascript/textobjects.scm
- queries/jsx/textobjects.scm
> feat(jsx): created the missing jsx queries

- lua/nvim-treesitter/textobjects/select.lua
Seems the keymap mode got lost after #232 
Closes #270
> fix(select): supply keymap mode

- lua/nvim-treesitter/textobjects/attach.lua
Should fix https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/278 edit: actually not sure whether it fixes the issue as a whole or rather just [@NEX-S problem](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/278#issuecomment-1236142161)
Not sure whether bad argument error was because `config_queries` was set to `nil` at the end of a loop or it simply went out of scope but introducing another local variable made it work
Took the liberty of slight refactoring, hope that's ok
> fix: nil query in closure when using mapping

- queries/php/textobjects.scm
- excludes the braces for all the inside queries
- add query for if statements
- add query for plain for loops
> feat: improve PHP queries

- lua/nvim-treesitter/textobjects/shared.lua
> fix: use `unpack` instead of LuaJIT/5.3 table.unpack

- queries/twig/textobjects.scm
Lately, [twig parser as been included in nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/pull/3529). 
This commit adds some textobjects for this language.
Thanks !!!!
> Introduce twig queries for comment, statement and parameter

- .github/workflows/lint.yml
Current workflow is failing. Use the same workflow code as nvim-treesitter
> ci: update stylua action

- queries/php/textobjects.scm
Not sure that is complete. 
Does conditionnals and loop should be considered as statement here ?
> Add php statement queries

- queries/php/textobjects.scm
Ref: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/304#issuecomment-1274512630
> feat(php): add arrow and anonymous function textobjects

- queries/haskell/textobjects.scm
> some refinements/fixes for the Haskell queries

- CONTRIBUTING.md
- queries/bash/textobjects.scm
- queries/ecma/textobjects.scm
- queries/elixir/textobjects.scm
- queries/julia/textobjects.scm
- queries/perl/textobjects.scm
- queries/ruby/textobjects.scm
- queries/vim/textobjects.scm
These are some textobjects I was already using locally.
I'll add support for a few more languages soon.
Closes #193
> feat: support regex patterns

- .github/workflows/update-readme.yml
- queries/ecma/textobjects.scm
Resolves #331.
I confirmed that, without this fix, the example doesn't work for javascript, but it will work if you change file extension to c or java.
I also confirmed that while loop works. It's a missing definition in the query file so I added it.
Plus, I fixed another issue with the GitHub Action test similar to #330.
> Added javascript (ecma) for loop query, and fix github action test

- lua/nvim-treesitter/textobjects/attach.lua
- lua/nvim-treesitter/textobjects/swap.lua
Revisiting #52 #55 . Would love to have a solution that works with Lua functions.
Problem: `vim.o.opfunc` doesn't seem accept Lua functions or I'm doing something wrong here
> feat: make swap functions repeatable

- queries/wgsl_bevy/textobjects.scm
wgsl_bevy was added in https://github.com/nvim-treesitter/nvim-treesitter/pull/4029
> feat: add support for wgsl_bevy

- .github/workflows/consistency_tests.yml
This adds the CI test described in #348, using the new repo.
> consistency tests

- lua/nvim-treesitter/textobjects/attach.lua
- lua/nvim-treesitter/textobjects/select.lua
> mapcheck before keymap.del

- lua/nvim-treesitter/textobjects/attach.lua
Fix type mismatch error introduced in #363 and reported in #365
> fix keymap mode type error

- README.md
Change to a more practical example, with gitsigns.nvim.
> readme better examples

- .github/workflows/tests.yml
> CI test on push

- lua/nvim-treesitter/textobjects/shared.lua
fix: https://github.com/nvim-treesitter/nvim-treesitter/pull/4300
> rename ts_utils.is_in_node_range -> vim.treesitter.is_in_node_range

- .github/workflows/check_query_files.yml
- .github/workflows/consistency_tests.yml
- .github/workflows/tests.yml
- .github/workflows/update-readme.yml
Fixes some broken CI scripts. Especially, update-readme will work now.
> Add tree-sitter-cli to CI

- README.md
> docs: updated doc for packer installation

- lua/nvim-treesitter/textobjects/shared.lua
Fixes #410 
In https://github.com/nvim-treesitter/nvim-treesitter/pull/4300, we deprecated the `is_in_node_range()` function in favour of the upstream neovim's implementation. However, it seems like the current nightly's implementation has been changed again, and it doesn't seem to accept table type as a node.
I don't know how to convert a table representation to `TSNode`. If you have a better idea of how to convert them, let me know. In the meantime, we can just use the original implementation to fix the bug.
> fix: select error

- queries/kotlin/textobjects.scm
Hey 👋🏾 
I worked locally on a better support for Kotlin and used the [playground](https://github.com/nvim-treesitter/playground) to define these text objects. They work pretty well for me during daily work. Though these are just the basics so far. 
I hope I made no mistakes.
Best regards ✌🏾
> Feat(kotlin): add bunch of new text objects

- queries/bash/textobjects.scm
Implements bash assignment queries
- `@assignment.inner`
- `@assignment.outer`
- `@assignment.lhs`
- `@assignment.rhs`
> feat: bash assignment

- lua/nvim-treesitter-textobjects.lua
- scripts/check-queries.lua
See https://github.com/neovim/neovim/pull/22761
> fix(deprecation): use query.get_files to avoid deprecation

- lua/nvim-treesitter-textobjects.lua
- lua/nvim-treesitter/textobjects/shared.lua
Closes nvim-treesitter/nvim-treesitter#4731
> fix: Use ts compat module for get_query

- scripts/update-readme.lua
Only show languages with at least one textobject defined
> feat: update readme filter languages

- queries/glimmer/textobjects.scm
> add glimmer support

- queries/v/textobjects.scm
> fix(v): update V textobjects to grammar changes

- queries/dart/textobjects.scm
Ref: nvim-treesitter/nvim-treesitter#5309
> fix(dart): Update queries from upstream

- queries/apex/textobjects.scm
`apex` is a new language recently added into nvim-treesitter already.
Here is the `textobjects.scm`
> feat(apex): add textobjects

- queries/nasm/textobjects.scm
Depends on nvim-treesitter/nvim-treesitter#5475
> feat(nasm): add textobjects

- queries/perl/textobjects.scm
Depends on nvim-treesitter/nvim-treesitter#5222
> feat(perl)!: update textobjects

- lua/nvim-treesitter/textobjects/select.lua
- scripts/minimal_init.lua
- tests/select/common.lua
- tests/select/python/selection_mode.py
- tests/select/python_spec.lua
@xvzc if you could review. I tested on my side and it works for #515.
> fix(select): patch #539 regression

- queries/readline/textobjects.scm
Text objects for `readline` files in case someone would want them
> feat(readline): text objects for GNU Readline

- queries/v/textobjects.scm
This change fixes the CI issue related to V
> fix(v): reflect new comment structure in parser

- queries/odin/textobjects.scm
Hello. 
This PR introduces queries for [odin](https://odin-lang.org/)
Thx for great plugin!
> Queries for odin

- queries/fennel/textobjects.scm
Updated queries to support the new parser.
> feat(fennel): update queries for new parser

- queries/vhdl/textobjects.scm
~~Only added a few of the possible options.~~
~~I have hopes to add more in the future.~~
I added a fairly comprehensive list for VHDL (tree-sitter-vhdl).
This has sped up my workflow, I hope this can help some others too.
> feat(vhdl): added support for VHDL

- queries/julia/textobjects.scm
Similarly to python queries, this PR also adds left side of assignment for capturing
> julia:improved assignment queries

- queries/haskell/textobjects.scm
> fix(haskell): tweak textobject queries

- .github/workflows/check_query_files.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- lua/nvim-treesitter-textobjects/shared.lua
- scripts/install_parsers.lua
- scripts/minimal_init.lua
- scripts/run_tests.sh
Also prevent running duplicate tests and fix typos.
> ci(tests): make tests actually run on `main`

- queries/zig/textobjects.scm
See https://github.com/nvim-treesitter/nvim-treesitter/pull/7097
> feat(zig): update queries to parser update

- README.md
- lua/nvim-treesitter-textobjects/shared.lua
> fix(shared): resolve metadata from directives

- queries/php/textobjects.scm
Hello!
This PR updates the PHP queries to be compatible with the BCs in https://github.com/tree-sitter/tree-sitter-php/pull/247
Thanks!
> deps(php): update php node renamed upstream

- queries/ecma/textobjects.scm
> feat(ecma): add `@function.*` capture for generator function

- queries/go/textobjects.scm
> fix(go): exclude braces for loops, conditions, class

- queries/lua/textobjects.scm
> Add lua support for `@comment.inner` and `@statement.outer`

- queries/toml/textobjects.scm
The failing tests are about something about python which I didn't touch; also they fail at other PRs as well, so I assume those can are not related to this PR?
> feat(toml): add `@comment.outer`

- queries/css/textobjects.scm
edit: the failing tests seem to be some python issue, so I assume they are irrelevant to this PR and can thus be ignored?
> feat(css): add `@comment.outer`

- queries/enforce/textobjects.scm
Basic support for classes, loops, functions and parameters textobjects for Enforce language
> feat(enforce): add queries

- queries/ecma/textobjects.scm
`@parameter.inner` and `@parameter.outer` works with import statements
> feat(ecma): import statements

- queries/ecma/textobjects.scm
Based on the discussion in #86
> feat(ecma): list or object elements as `@paramter`
