queries/rust/textobjects.scm

Related to https://github.com/nvim-treesitter/nvim-treesitter/issues/544
```rust
#[derive(Debug, PartialEq)]
struct Test {}
fn main() {
}
```
For example, switching `Debug` and `PartialEq`

Add `meta_arguments` to @parameter.inner for Rust

---

.github/workflows/update-readme.yml
README.md
scripts/update-readme.lua

The new version no longer requires exposing
`nvim-treesitter.query.get_query_string`.
https://github.com/nvim-treesitter/nvim-treesitter/pull/515#discussion_r492550885

Fix update-readme.lua

---

queries/cpp/textobjects.scm
queries/javascript/textobjects.scm
queries/tsx/textobjects.scm
queries/typescript/textobjects.scm

https://github.com/nvim-treesitter/nvim-treesitter/pull/564
Seems to work :-). One remark: it's pretty easy to forget the `:` and to find out what's wrong. Also *no trailing whitespaces*

Add inheritance modelines

---

README.md
queries/go/textobjects.scm

This way we can use swap with Go.
There are some limitations in the query though, opening as a draft to see if I can get some input from others. With the current parser, the following function has only one parameter_declaration:
```go
func DoThing(i, j int) {}
```
This seems to be a problem with the Go parser? I'll keep playing around with it in the playground.

queries/go: add @parameter.inner

---

autoload/nvim_treesitter_textobjects.vim
lua/nvim-treesitter-textobjects.lua
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/lsp_interop.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/textobjects/select.lua
lua/nvim-treesitter/textobjects/shared.lua
lua/nvim-treesitter/textobjects/swap.lua
scripts/update-readme.lua

Add a command for selecting a textobject. More commands can be added by filling the command dictionaries of the submodules (this should be upstreamed to do on registration of every nvim-treesitter module).
@weilbith If you want more commands you can create a PR. You need to do the remap for select and operator pending mode (their was a comment why select is better than visual mode for this plugin).
I guess it's more comfortable to set the mappings with a Lua plugin like
https://github.com/svermeulen/vimpeccable
```
vimp.nnoremap('<leader>hw', function()
print('hello')
print('world')
end)
```
or a own abbreviation
https://github.com/kyazdani42/dotfiles/blob/7a75655e387c0b4ec021f91d631027219b05b902/config/common/nvim/lua/init.lua#L69

Fix #20: Add TSTextobjectSelect

---

CONTRIBUTING.md
queries/c/textobjects.scm
queries/cpp/textobjects.scm
queries/python/textobjects.scm
queries/rust/textobjects.scm

Addresses: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/22
Requires: https://github.com/nvim-treesitter/nvim-treesitter/pull/657
It only works if your cursor is between the parameter or and the end character of the ",". I try to add @stsewd select next textobject soon to make it also work on spaces before the parameter

Add @parameter.outer for Python/C/C++

---

queries/php/textobjects.scm

I took the liberty to add some queries for php. I still new on the query language. I was not able to get `if_statement`
to work correctly at the moment. Also, I wanted the ability to select the body of a function, excluding the `{` and `}`.
I reviewed [Add @parameter.outer for Python/C/C++](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/23) PR but was not able the result that I am looking for. I am not sure if excluding the braces is feasibly in treesitter at the moment.

feat: Added queries for php

---

queries/c/textobjects.scm

Capture declarations commonly found in header files.
```
bool foo(int bar);
```

C: add textobject for function declarations

---

lua/nvim-treesitter/textobjects/select.lua

Fixes #36.
Example Python code:
```python
def a():
print("Hello")
def b():
print("World")
```
Now with cursor inside `print("World")` these are now possible:
- `Vaf` selects lines 3-4.
- `dVaf` deletes lines 3-4 (utilizing operator-pending linewise mode).
There is one minor corner case: with cursor inside `def b()` using `Vaf` selects all lines 1-4. This seems to be because of how `nvim-treesitter.ts_utils.update_selection()` works: it updates selection to the "nearest" textobject containing the _whole_ current selection. After using `V` on line `def b()`, selection goes outside of scope of `b()` and the whole enclosing function is selected (if there is no enclosing function and indent is due to outer class, for example, nothing is selected). Currently I don't see a way of fixing this …

Allow linewise selection

---

queries/typescript/textobjects.scm

@fsouza Some parameter queries will stop to work for typescript

Fix typescript textobjects for nvim-treesitter/nvim-treesitter#1000

---

queries/vue/textobjects.scm

Adds textobjects for attributes and Vue directives
Testable with this file:
```
<template>
<SomeComponent my-attribute :my-directive="false" @my-event="method"/>
<div class="abcd">hello</div>
</template>
```
If I bind move_next to eg. `<f2>`, I notice that if I write `c<f2>` nothing happens. I expected it'll work the same as `cw`. Did I implement something wrong?

Add super basic vue support

---

doc/nvim-treesitter-textobjects.txt
lua/nvim-treesitter-textobjects.lua
lua/nvim-treesitter/textobjects/select.lua
lua/nvim-treesitter/textobjects/shared.lua

Haven't added docs, if you think this functionality is in scope of the plugin let me know and I can add docs.
This allows `select` to look ahead in the syntax tree if it cannot find a match with the cursor position in it. E.g.
```lua
local x = 'hello' -- <- your cursor is here and you press `vaf`
function foo()  -- ----
print('foo')  --     | <- this would be selected
end             -- ----
```
Sample Config:
```lua
treesitter.setup {
textobjects = {
select = {
enable = true,
lookahead = true,
keymaps = {
['af'] = '@function.outer',
}
},
}
}
```

Add textobjects.select.lookahead option to select the next textobject

---

README.md

```
-- Automatically jump forward to textobj, similar to targets.vim 
lookahead = true,
```

add lookahead readme

---

queries/typescript/textobjects.scm

The current type def does not apply to "optional parameters", like "c" below.
```
function fn(a, b, c?) {
}
Treesitter:
function_declaration [78, 0] - [79, 1]
name: identifier [78, 9] - [78, 11]
parameters: formal_parameters [78, 11] - [78, 21]
required_parameter [78, 12] - [78, 13]
identifier [78, 12] - [78, 13]
required_parameter [78, 15] - [78, 16]
identifier [78, 15] - [78, 16]
optional_parameter [78, 18] - [78, 20]
identifier [78, 18] - [78, 19]
body: statement_block [78, 22] - [79, 1]
```

fix typescript optional params

---

README.md
queries/c/textobjects.scm
queries/cpp/textobjects.scm
queries/dart/textobjects.scm
queries/python/textobjects.scm
queries/rust/textobjects.scm

Fixes #85
This will actually delete the preceeding comma for all arguments expect the first parameter. This leaves the argument list better formatted in most cases (by not leaving an extra space as it used too). The first parameter will still leave a space, which we don't know how to fix currently
This PR also makes parameter.outer delete entries from tuples, list and dictionaries in python.
Also, It makes parameter.* cover template parameter/argument lists and lambda capture lists in c++.
(related to #86)
We may open some more pull requests for correcting parameter handling in other languages as we get time

Make parameter.outer delete the preceeding comma in python, dart, rust, c/c++, and some other changes

---

queries/julia/textobjects.scm

This should add inner text objects for julia language. I'm still learning treesitter queries, so some of them might not be the most elegant solution, but I have tested them all and they seem to work with every edge case I could think of.
The one thing I couldn't figure out is how to get the let_statement inner.block to not also include the variable declarations at the start of the block. Best I could manage was to make it not include the first variable declaration, but I thought that it was better to have it consistent but wrong so I left it as including all of them.

Added Julia inner text objects

---

queries/fish/textobjects.scm

The objects are limit due to choices in the grammar and the lack of ability to select groups of sibling nodes of the same type.

Adds fish shell textobjects

---

queries/ruby/textobjects.scm

I have added all the inner variants of the supplied text objects as well
as 
- adding modifier variants of conditionals and loops, 
- comments and
- parameters support
I have tried keep these query's efficient but there may be room for improvement
[](https://github.com/hlissner/doom-emacs/pull/5401)

Add more ruby text objects

---

queries/ruby/textobjects.scm

I saw this [PR](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/107) added some text objects for Ruby, but it has some bugs and unhandled cases.
So I created this PR to fix it. Hope you can take a look.
I'm Ruby dev, so I'm very glad if you can mention to me if have any changes in the Ruby text object, I can check it to be sure it's correct.
Fix class, function and block text objects, tested with many cases from:
https://github.com/tree-sitter/tree-sitter-ruby
Add some cases for parameter text object.

Fix some ruby text objects

---

README.md
queries/elixir/textobjects.scm

Adding Elixir text objects.
Unfortunately, pretty much everything in the elixir grammar is a function or a call, so it's pretty hard to match some of the requested captures, as a lot of them would just be redundant. I followed the javascript queries to get as close as I can to matching what that matches and it's pretty spot on.
Adding:
- `@comment.outer` to match any `#comment`, though there was already a query to get module docs
- `@conditional.outer/inner` for all `if/cond/case`
- `@parameter.inner/outer` which matches arguments and parameters.
Altered:
- `@class.inner/outer` to remove the unneeded brackets.
Updating readme to match what was already there and what's new, as well.

Add elixir queries

---

queries/typescript/textobjects.scm

The current tsx support is totally non-functional, with this change many things work. As far as I can tell it supports everything typescript supports.
It might not be the ideal future direction of the plugin, but at least some things work for now so maybe it's worth considering this as a pragmatic change for the time being?

Fix tsx support

---

queries/python/textobjects.scm

Consider following code:
```pyhton
l = [1,2, |"str"]
```
@parameter.inner does not capture any node.  
The syntax tree of this list is
```
list:
integer:
integer:
string:
```

Python query: fix tuple and list @parameter.inner

---

queries/ruby/textobjects.scm

Outer was selecting the entire top line instead of just the do
Example:
```ruby
foo.tap do
bar
end
```
Before:
Selecting @block.outer selecting all of the following
After:
Selects from do to end. Does not include `foo.tap `

Update Ruby block selections

---

queries/fennel/textobjects.scm

Not actually sure why the GH action failed with the error it did, but here's something.
Again, there was [some tree-sitter changes for Fennel](https://github.com/TravonteD/tree-sitter-fennel/pull/31); hopefully these fixes are enough.

Small Fennel fixes

---

README.md
doc/nvim-treesitter-textobjects.txt

If a user copies them,  find themselves with a very common operation in vim delete up to a word or backwards. I would think is better to recommend something that doesn't overwrite such a basic editor operation.
Speaking from experience 😄

fix: change example mappings for peek_definition_code

---

queries/ruby/textobjects.scm

Greatly improves the performance of ruby textobjects
Before:
705-715ms
After:
480-500ms
Commenting out this entire file brings performance down too 420-430ms. Any tips to get a few more ms out of these queries?

Improve ruby text object performance

---

queries/java/textobjects.scm
queries/rust/textobjects.scm

* Rust and Java comment text objects
* Fix trailing whitespace in edited files

Rust and Java comment text objects and fix trailing whitespace.

---

.github/workflows/check_query_files.yml
lua/nvim-treesitter-textobjects.lua
lua/nvim-treesitter/textobjects/select.lua
lua/nvim-treesitter/textobjects/shared.lua

Lookbehind is like lookahead but in the other direction. This can be useful if you want to select the function name from the function body with a custom query. If lookahead and lookbehind are configured as true, lookahead is dominant. As a further improvement i suggest that lookahead and lookbehind should be assigned to each keymap individually, because this will allow bindings like vim's integrated f for search forward and F for search backward.

Added lookbehind functionality

---

queries/elm/textobjects.scm

Adds
* comment.outer
* conditional.inner
* conditional.outer
* function.inner
* function.outer
* parameter.inner
* parameter.outer
I tried to add @block.inner and @block.outer for let/in expressions, but as of yet the query necessary given the available AST structure is beyond me. 
The behavior of @function.outer in particular is to my tastes, but may run counter to behavior in other languages. 
The full module level function block in Elm is composed of up to three parts, the function itself and one or both of a type annotation and doc comment above the function. The current implementation will grab these for @function.outer as greedily as possible. 
I feel selecting the type annotation is certainly correct and matches the existing behavior of python including decorators in …

Adds relevant text objects for Elm

---

.github/workflows/update-readme.yml

Fixes #138
Right now, due to branch protection rules (to enable auto-merge) prevent the bot from pushing to master

ci: open a PR to update README

---

scripts/update-readme.lua

More easy to check what textobject the emoji is referring to. Tried using a check mark instead of the green square, but github colors those as gray
This is how it looks like with squares

README: improve table of supported textobjs

---

queries/javascript/textobjects.scm

This case is missing
```js
let local = function () {
let a = 'this!'
}
```

JS: add function textobject

---

queries/go/textobjects.scm

This PR fixes the `@parameter.outer` queries for Go for the case where the comma optionally trails the parameter. They were previously making ranges using the same range as for the case where the comma precedes the parameter. This meant that if you had a config like
```
require('nvim-treesitter.configs').setup {
textobjects = {
select = {
enable = true,
keymaps = {
['aa'] = '@parameter.outer'
}
},
}
}
```
and did a `daa` with your cursor in this position
```
func Add(x| int, y int) int {
return x + y
}
```
then you would end up with 
```
func Add(|, y int) int {
return x + y
}
```
rather than 
```
func Add(| y int) int {
return x + y
}
```

Fix Go @parameter.outer not including trailing commas

---

queries/php/textobjects.scm

This code was stolen from https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/6ee11ac62681eb2eb8104a4ce509a9a861672cb5/queries/lua/textobjects.scm#L16-L32
I don't understand what the following block is about:
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/6ee11ac62681eb2eb8104a4ce509a9a861672cb5/queries/lua/textobjects.scm#L34-L45

Add support for parameter.outer for PHP

---

queries/java/textobjects.scm

This fixes the nightly running CI that failed due to the update of the Java parser.

fix(java): use line_comment/block_comment instead of comment

---

queries/lua/textobjects.scm

nvim-treesitter switched to a different Lua parser in https://github.com/nvim-treesitter/nvim-treesitter/pull/2272, which requires adaptation of queries
@MunifTanjim

fix(lua): adapt queries to upstream switch

---

README.md
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/select.lua
lua/nvim-treesitter/textobjects/shared.lua

This feature hasn't been working for a long time.
And users can already override or extend textobjects
using the query files instead.
Options like these were working
```
{
["aF"] = {
["python"] = "@foo"
}
}
```
Should we keep compatibility for those?
But that form wasn't documented, so not sure if there are people using it.
Closes https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/65
Closes https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/66/

Update per-language textobjects instructions

---

queries/fennel/textobjects.scm

See https://github.com/TravonteD/tree-sitter-fennel/pull/34/files
The query tries to select from `[` to everything until ")"`. This seems to be be the behavior before. Though I would either select the loop body or the bindings....

fix(fennel): each_clause does no longer exist

---

queries/latex/textobjects.scm

Seems that [nvim-treesitter/nvim-treesitter#2591](https://github.com/nvim-treesitter/nvim-treesitter/pull/2591) has changed the `command` query into `generic_command`. If we don't modify this query in textobject. An error will occur when opening a latex file.

fix(latex): update queries

---

queries/r/textobjects.scm

This should fix #198 
I hadn't mapped the `@_start`, my mistake.

fix(r): parameter and argument

---

queries/elixir/textobjects.scm

This patch extends @function.inner and @function.outer to also support
anonymous functions of the style
```
fn(x) ->
x * x
end
```

[Elixir] Adds support for anonymous functions

---

queries/javascript/textobjects.scm

#196 excludes curly braces for `@function.inner`, but not for arrow functions in JavaScript.
I'm completely new to treesitter queries and Scheme so feel free to critique my solution.

Exclude curly braces on @function.inner in JavaScript arrow functions

---

doc/nvim-treesitter-textobjects.txt
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/textobjects/shared.lua
lua/nvim-treesitter/textobjects/swap.lua

While I like this plugin a lot, the biggest complaint that I have (and have read) about it is that it requires a lot of keybinds to use effectively since they must be one per-capture-group per-action. Furthermore, many people (myself included) don't really care about the specific capture group being acted upon; rather, they want to act upon the first or closest capture group that makes sense for the action they're trying.
To be more concrete: I work a lot in Python. What I really want from this plugin are two things: (1) to easily move between major, meaningful parts of a file, and (2) to easily swap elements of lists (of arguments, dictionary entries, etc.). The over-broadness of `@parameter`, as pointed out in PR #86, is evidence that I am not alone in this desire, at least for the …

Change config for swap and move to take a table of capture groups to increase configurability

---

queries/scala/textobjects.scm

Previously `@function.inner` would only capture function bodies wrapped in braces:
```scala
// Would capture
def foo: Int = {
...
}
// Wouldn't capture
def foo: Int = 3 * 10
```

Improve @function.inner for scala

---

lua/nvim-treesitter/textobjects/select.lua

Recent changes to make the selection modes configurable broke specifying
a charwise selection mode as part of the operator (e.g. `dvif` where
`if` is mapped to `@function.inner`). I believe charwise selection only
worked previously because it was the default used by
`ts_utils.update_selection`. We don't specify charwise selection in the
table under `elseif method == "operator-pending" then` in `select.lua`,
meaning we can't manually specify charwise selection if
`config.selection_modes[query_string]` is mapped to `V` or `<c-v>`.
This change adds an entry for `nov` (Operator-pending (forced
charwise)).
Fixes #236

Selection no longer allows ad-hoc charwise selection

---

README.md
lua/nvim-treesitter/textobjects/select.lua

This is an initial attempt to handle preceding/succeeding whitespace of textobjects and I'm looking for feedback. Initially mainly about the behaviour, which is opt-in. I think the current implementation can be made much better but that's a second question and I would first like to know if this makes sense :)
What this change does is that if the user enables it, it expands any textobject to include preceding or succeeding whitespace. It always tries to include any preceeding whitespace and if there is none instead tries to include succeeding whitespace (but never both). The ides is that it would work much like eg the built-in `aw`, `ap` etc. See the following screencast for a more concrete view:
https://user-images.githubusercontent.com/23341710/181994568-52c018b8-861d-4ec9-a2e9-847e88100e …

include surrounding whitespace

---

queries/heex/textobjects.scm

It's a subset of the `html` queries; and the `element` node has been renamed to `tag`, because that's the name in the `heex` grammar

feat: add support for heex

---

queries/ruby/textobjects.scm

With the merging of https://github.com/tree-sitter/tree-sitter-ruby/pull/224 we now have access to a body node for classes, methods, and blocks which greatly simplifies the queries for capturing the inner bits of these objects. It also is a huge performance improvement.

Update ruby queries after new body changes

---

lua/nvim-treesitter/textobjects/move.lua

Added basic capability to enumerate movement operations to allow faster jumping across textobjects. This allows the user to do something like 3]m or 3[m to move forward/backward by a multiple/count of the motion. 
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/217

Allow count motion movement

---

README.md

There is an extra } in the example setup script

Update README.md - Remove extra }

---

queries/javascript/textobjects.scm

Currently none of the builtin textobjects (1 - 21) work for javascript. 
By changing the inheritance from `(ecma, jsx)` to just `ecma` it seems that at least `@function.outer` and `@function.inner` work fine (at least for simple javascript files). 
If the maintainers are open to this change then I would edit also the README.md to mark all the textobject that are actually supported.

Enable javascript textobjects

---

queries/c/textobjects.scm
queries/c_sharp/textobjects.scm
queries/dart/textobjects.scm
queries/ecma/textobjects.scm
queries/fennel/textobjects.scm
queries/go/textobjects.scm
queries/haskell/textobjects.scm
queries/java/textobjects.scm
queries/julia/textobjects.scm
queries/lua/textobjects.scm
queries/python/textobjects.scm
queries/rust/textobjects.scm
queries/zig/textobjects.scm

This PR unifies `@call.inner` captures across languages that currently support it. Resolves #195.
Most languages currently have `@call.inner` select arguments *with* parenthesis.
General rule for selecting inner function call is taken to be "all arguments, without parenthesis, of function call". As a reference, captures from [cmake](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/4234c446d14370b3cd7604bd8e2e51ae2680f5ee/queries/cmake/textobjects.scm#L26-L30) are used, which after language-specific tweaks seem to work for most of the cases.
Notes:
- Although Cmake is already fully implemented, it is not mentioned in README.md (missing support of `@call.inner`). Didn't do anything, as it is an issue of 'scripts/update-readme.lua'.
- Having separate queries for …

Unify `@call.inner` capture

---

queries/lua/textobjects.scm

This is a follow up to #250. I made its second commit in an attempt to clean Lua queries a little bit. But without proper extensive testing it inadvertently started rejecting function calls without arguments. This seems to fix it.
Sorry for the inconvenience.

Fix `@call.outer` in Lua to allow call with no arguments

---

lua/nvim-treesitter/textobjects/select.lua

get_char_after_position might now always exist

fix: guard against invalid line

---

README.md
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/select.lua

Fixes #232
@danielo515 are you using https://github.com/folke/which-key.nvim ? This should set description for this plugin. How can I register for telescope's which_key? Do want to additionally want to overwrite the automatically generated descriptions?
I don't think there is a generic way to set a description for a key mapping. ~~@folke maybe it would be an idea to add a "description" key to `opts` of `nvim_buf_add_keymap` that can be retrieved by new API function? It is difficult for third party plugins to annotate their keybindings that is not taylored to one specific which-key plugin ~~ (`nvim_buf_add_keymap` already has `desc`)

Register key mappings to which-key

---

queries/ecma/textobjects.scm

Fixes #215
Let me know if this dot had any reason for being there, but removing it fixed @function.outer in JavaScript for me.

fix: arrow function outer not being captured

---

lua/nvim-treesitter/textobjects/attach.lua

Bugfix for: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/273
and : https://github.com/ray-x/navigator.lua/issues/225

skip keymap for lang not enabled

---

lua/nvim-treesitter/textobjects/select.lua

Fixes #279
@fsouza https://github.com/AckslD @NEX-S should be go back to traditional set_keymap?

fix: roll back nvim_buf_set_keymap instead of keymap.set

---

queries/python/textobjects.scm

This adds support for top-level statements in Python `@statement.outer`, which enables statement selection in a scripting context where there is no enclosing block.

feat: python support for top-level @statement.outer

---

README.md
lua/nvim-treesitter/textobjects/select.lua

This allows `selection_modes` and `include_surrounding_whitespace` to optionally be functions for dynamic settings.
For example I have now the following settings:
```lua
{
...
-- for example only include whitespace for a<something> mappings and not i<something>
include_surrounding_whitespace = function(opts)
local obj, scope = unpack(vim.split(opts.query_string, '.', {plain = true}))
return scope == 'outer'
end,
-- for example only use linewise for functions and classes in python
selection_modes = function(opts)
if vim.bo.filetype == 'python' then
return {
["@class.outer"] = 'V',
["@class.inner"] = 'V',
["@function.outer"] = 'V',
["@function.inner"] = 'V',
}
end
end,
...
}
```

feat(select): allow settings for modes and whitespace to be callbacks

---

README.md

...when overriding/extending textobjects.
I just found out that, in v0.8.0, you're supposed to start the file with `; extends`, otherwise the file will be ignored (only one query file will be considered).
See https://github.com/neovim/neovim/pull/20105/ and https://github.com/neovim/neovim/issues/20172

Clarify the need for extends modeline

---

lua/nvim-treesitter/textobjects/shared.lua

I found it hard to use the "#make-range!" pattern to create a text object to select inside JavaScript template strings
```js
const templateString = `
Hello world
`
```
I tried to use something like this but it didn't work:
```scheme
(template_string . "`" _ @_start _? @_end "`" . (#make-range! "mytextobject" @_start @_end))
```
I'd expect this to work though, but it didn't:
```scheme
((template_string) @mytextobject (#offset! @mytextobject 0 1 0 -1))
```
So this patch will make it work now, the offset directive will be respected.

Respect offset directive when getting text object range

---

lua/nvim-treesitter/textobjects/lsp_interop.lua

To make ftplugin work in preview buffer (e.g. set tabstop for special filetype)
Also enable treesitter highlighting #210

feat: set filetype in peek_definition_code

---

queries/julia/textobjects.scm

- Rename `compound_expression` to `compound_statement`
- Add `quote_statement`
- Add `short_function_definition` (and remove old function call hack)
- Rename `subscript_expression` to `index_expression`
- Organize patterns

Update julia queries

---

queries/rust/textobjects.scm

I briefly checked and it seems `{if,while}_let_expression` can be replace 1:1 by existing `{if,while}_expression` queries.
This PR also removes `meta_arguments` related queries because it was giving the same error.
Fixes #316

fix(rust): remove `if_let_expression` and `while_let_expression`

---

.github/workflows/check_query_files.yml

The latest Ubuntu doesn't come with libfuse2, so the appimage wouldn't run without this dependency as shown below.  
This pull request fixes this issue and re-enables checking query files Action.
Problem:  
Fix:

Fix GitHub Actions check query files

---

lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/lsp_interop.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/textobjects/swap.lua

This pull request resolves #6, to make the move operation consistent with vim's behaviour.
Now you can move in visual mode or operator-pending mode.
For example,
`v]M` will select until the end of the function, assuming the key binding following the README.  
`dv]M` will delete until the end of the function.

Move object supports visual and operator-pending modes

---

queries/r/textobjects.scm

This pull request adds queries for @statement.outer in R. The design will properly detect top-level statements and statements within a function, loop, or conditional block
One slight weirdness of this design is that selecting the current statement from an empty line in a  brace_list selects the enclosing top-level statement, e.g. if the cursor is at the `|` character in the following example, a `@statement.outer` query will select the whole if statement.
```R
if (TRUE) {
1+1
|
2+2
}
```
I think this is acceptable behavior, and it would be challenging to change without causing other breakages. Just wanted to surface this in case there are concerns

feat: R @statement.outer support

---

queries/julia/textobjects.scm

index_expression has no longer `","` children. The children are now either `vector_expression`, `matrix_expression` or `comprehension_expression`.
@kiyoon feel free to merge. Each PR should have at least one review of one of the maintainers. `nvim-treesitter-textobjects` has a nightly CI that detects breakages like this one.
@clason had the idea to move textobject queries back to the upstream repo. We could also test nvim-treesitter-textobject in the main repo to be warned when a change would break one of the textobject queries. Since the revision of this plugin moves independently from nvim-treesitter. We can't guarantee that parser and queries match.

fix(julia): fix `index_expression`

---

lua/nvim-treesitter/textobjects/select.lua

Using `:` in the mapping causes some UIs to glitch when repeating a command (`.`) on a textobject. `<cmd>` prevents that.

Use <cmd> in keymapping to prevent flicker on some UIs

---

lua/nvim-treesitter/textobjects/select.lua

This reverts commit 4c9bcaaabcc9b978871b97ee6142417f77aa0b53.
Fixes #344

Revert "Use <cmd> in keymapping to prevent flicker on some UIs"

---

queries/julia/textobjects.scm

See https://github.com/tree-sitter/tree-sitter-julia/pull/85 and https://github.com/nvim-treesitter/nvim-treesitter/pull/4016

fix(julia): Remove `type_parameters` field name

---

lua/nvim-treesitter/textobjects/select.lua

@theHamsta Could you test that with the suggested changes made in nvim-treesitter (https://github.com/nvim-treesitter/nvim-treesitter/pull/4015)?
On my end, everything seems to be working well. In particular, I can do `Vaf` or `vaf` and it will respect the selection mode. If user has put a preference for selection mode in config, then config will take precedence.
*Edit*: ~I need to remove debug print statement.~
I also reintroduced the `<cmd>` instead of `:` in mapping. We could translate it directly to `vim.keymap.set` in this PR.

fix (select): Rewrite detect_selection_mode function

---

README.md
doc/nvim-treesitter-textobjects.txt
lua/nvim-treesitter-textobjects.lua
lua/nvim-treesitter/textobjects/lsp_interop.lua

Add the possibility to specify a maximum height for floating window, so it does not fill all the screen.

feat(lsp_interop): Add max win height option for floating window

---

README.md
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/lsp_interop.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/textobjects/select.lua
lua/nvim-treesitter/textobjects/shared.lua
lua/nvim-treesitter/textobjects/swap.lua

Before merging #359 I wanted to show you this.
At the moment, my keymaps are quite polluted.
```lua
goto_next_start = {
["]m"] = "@function.outer",
["]f"] = "@call.outer",
["]d"] = "@conditional.outer",
["]o"] = "@loop.outer",
["]s"] = "@statement.outer",
["]a"] = "@parameter.outer",
["]c"] = "@comment.outer",
["]b"] = "@block.outer",
["]l"] = { query = "@class.outer", desc = "next class start" },
["]]m"] = "@function.inner",
["]]f"] = "@call.inner",
["]]d"] = "@conditional.inner",
["]]o"] = "@loop.inner",
["]]a"] = "@parameter.inner",
["]]b"] = "@block.inner",
["]]l"] = { query = "@class.inner", desc = "next class start inner" },
},
goto_next_end = {
["]M"] = "@function.outer",
["]F"] = "@call.outer",
["]D"] = "@conditional.outer",
["]O"] = "@loop.outer",
["]S"] = "@statement.outer", …
```

Gradual movement (regex query string, goto_next and goto_previous without specifying start / end)

---

README.md
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/textobjects/repeatable_move.lua
lua/nvim-treesitter/textobjects/swap.lua

Implements #340 
Supports normal, visual and operator-pending modes, `v:count1` count repeat, and optionally builtin f, F, t, T mappings if you want to use the same `;` bindings.
```lua
local tstextobj_move = require "nvim-treesitter.textobjects.move"
-- Repeat movement with ; and ,
-- ensure ; goes forward and , goes backward
vim.keymap.set({ "n", "x", "o" }, ";", tstextobj_move.repeat_last_move_next)
vim.keymap.set({ "n", "x", "o" }, ",", tstextobj_move.repeat_last_move_previous)
-- vim way: ; goes to the direction you were moving.
-- vim.keymap.set({ "n", "x", "o" }, ";", tstextobj_move.repeat_last_move)
-- vim.keymap.set({ "n", "x", "o" }, ",", tstextobj_move.repeat_last_move_opposite)
-- Make builtin f, F, t, T also repeatable with ; and ,
vim.keymap.set({ "n", "x", "o" }, "f", …
```

Repeat movements like `;` and `,`

---

lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/lsp_interop.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/textobjects/select.lua
lua/nvim-treesitter/textobjects/swap.lua

Since #360 there is a new logic to adding keymaps because we allowed to set queries from another group. However, in detaching it doesn't consider the logic the same way.  
I think it makes more sense to remember the successful keymaps per buffer and use them for detaching. Also, added pcall to fallback silently if unsetting keymap fails.
The issue seems to have started happening in #362 and although it's been fixed for some people, it is still a problem for others (see comments from the issue below).

different logic for detaching keymaps (remember attached keymaps)

---

CONTRIBUTING.md
queries/bash/textobjects.scm
queries/c/textobjects.scm
queries/css/textobjects.scm
queries/dockerfile/textobjects.scm
queries/ecma/textobjects.scm
queries/java/textobjects.scm
queries/kotlin/textobjects.scm
queries/lua/textobjects.scm
queries/nix/textobjects.scm
queries/python/textobjects.scm
queries/r/textobjects.scm
queries/rust/textobjects.scm
queries/scss/textobjects.scm
queries/toml/textobjects.scm
queries/vim/textobjects.scm
queries/yaml/textobjects.scm

Because floating-point numbers and CSS colors can't be selected with `iw`.

feat: add textobject for number literals

---

.github/workflows/tests.yml
lua/nvim-treesitter/textobjects/repeatable_move.lua
scripts/ci-install-ubuntu-latest.sh
scripts/minimal_init.lua
scripts/run_tests.sh
tests/repeatable_move/common.lua
tests/repeatable_move/python/aligned_indent.py
tests/repeatable_move/python_spec.lua
tests/select/common.lua
tests/select/python/aligned_indent.py
tests/select/python_spec.lua

Added tests for:
1. repeatable move builtins (by comparing actual movement from vim's builtins)
2. select consistency (`viad`, `cia`, `dia` should be the same)
One test fails because currently there is a glitch.
Using https://github.com/nvim-treesitter/nvim-treesitter/pull/4228 will make all tests pass.
By doing this, I noticed that the builtin find movements we implemented have a very minor difference.  
For some reason, if you use `t` and repeat with `;`, then the default count is 2, so `;` and `2;` should work the same way.

Add tests, Make builtin find consistent (when t and repeating)

---

queries/elixir/textobjects.scm

With the previous matches if you triggered a `@class.inner` change and you happened to be in the last block of a module it would only change that block instead of deleting all the blocks of the module.
For example with a file such as this where `|` is the cursor:
```elixir
defmodule Test do
def hello() do
IO.puts("hi")
end
def oi() do
|IO.puts("oi")
end
end
```
After the edit you'd have:
```elixir
defmodule Test do
def hello() do
IO.puts("hi")
end
|
end
```
The previous approach was using a single query and then trying to build
a range over all children of a block, or in the case of a single child
using it as the start and end. I could not for the life of me figure out
a way to write this to work. As soon as I broke it out to two queries:
one with a make range and one that just captures …

 fix(elixir): handle last block bug for @class.inner 

---

lua/nvim-treesitter/textobjects/repeatable_move.lua
tests/select/common.lua
tests/select/python_spec.lua

Fixes #381 and adds tests to check the equality of `vfid`, `dfi` and `cfi`  
plus `v]a`, `d]a` and `c]a` (`@parameter.outer`)
Note that this is not limited to built-in finds. Currently the test fails because the node movements have the same error.  
https://github.com/nvim-treesitter/nvim-treesitter/pull/4283 will make the failing test pass.

Fix: Operator-pending missing last character in builtin finds

---

queries/elixir/textobjects.scm

Added a capture to the inner contents of an elixir documentation tag. These tend to come in two forms: the string form and the options form
String form
```elixir
@moduledoc """
Hey look! Some documentation.
"""
```
Performing a `@comment.inner` change on the documentation would leave you in the following state.
```elixir
@moduledoc """|"""
```
I tried the best I could to have the state be the following but I don't know if its possible easily, how I have it is the next best thing.
```elixir
@moduledoc """
|
"""
```
Options form of documentation elements.
```elixir
@doc deprecated: "Use .... instead"
```
Same `@comment.inner` edit would get you to this state.
```elixir
@doc |
```

Add @comment.inner to elixir documentation elements

---

queries/rust/textobjects.scm

Things like:
```rust
pub trait Empty {}
pub struct Foo;
pub trait Bar {
fn foo();
}
pub enum MyEnum {
}
```
aren't being captured, because the `*.inner` queries are requiring at least one node inside the parent node.

Rust: support empty declarations

---

.github/workflows/consistency_tests.yml
lua/nvim-treesitter-textobjects.lua
lua/nvim-treesitter/textobjects/attach.lua
lua/nvim-treesitter/textobjects/shared.lua
queries/ecma/textobjects.scm
queries/lua/textobjects.scm
queries/python/textobjects.scm
queries/rust/textobjects.scm
queries/vim/textobjects.scm
scripts/check-queries.lua

This PR includes rewriting using `vim.treesitter` over `nvim-treesitter` partially.
The problem with the previous method is that there is no association with @*.inner and @*.outer textobjects. So even if you're within the range of an outer area, the inner will select something wrong.
The problem occurs when the cursor is in between the outer range and inner range. In that case, the `@function.inner` will choose the larger context like the main function.
This patch provides solution for #335, #328, #125, and #15.
Additionally, I wrote `@assignment.outer`, `@assignment.inner`, `@assignment.lhs`, `@assignment.rhs` queries for python, lua, rust, vim, and js (ecma). This way you can select the left hand side (lhs) from the right hand side cursor (as the cursor is within the range of outer). …

Feat: prefer select within outer range

---

README.md

Add reminder to README.md on how to use alternative query groups, because I forgot and didn't know where to look up.

docs: add documentation hint for `query_group`s

---

CONTRIBUTING.md
queries/c/textobjects.scm
queries/lua/textobjects.scm
queries/python/textobjects.scm
queries/rust/textobjects.scm
queries/vim/textobjects.scm

But sadly, Rust's return textobject works only for explicit return statements, and doesn't work for most functions because [most functions return the last expression implicitly](https://doc.rust-lang.org/stable/book/ch03-03-how-functions-work.html#functions-with-return-values) (without explicit `return` keyword).

feat: add return textobject for C/CPP/Lua/Python/Rust/Vim

---

queries/python/textobjects.scm

```python
--- cic ---
```
and
```python
#test
--- cic ---
#|
```
where `|` denotes the cursor.
I added the first as 'special case', because I think that is (and should be) how most programmers use comments: *always* having a space after the comment marker. Adding this as a special case skips having to add the space every time after something like `cic`.

python: add `@comment.inner`

---

queries/v/textobjects.scm

The following textobjects are added:
I've based most queries on Go's from current master.

v: Add V textobjects

---

queries/fish/textobjects.scm

Fish's treesitter has a weird way of not using unique field values.
```fish
set -q x "hello"
```
Gives:
```
command [0, 0] - [0, 16]
name: word [0, 0] - [0, 3]
argument: word [0, 4] - [0, 6]
argument: word [0, 7] - [0, 8]
argument: double_quote_string [0, 9] - [0, 16]
```
I can't seem to get *all* arguments, to use e.g. for `@call.inner`. Let me know if this is possible, then I'll add the functionality of those

fish: add textobjects

---

README.md

Add a section of rules that explains how to name queries.
Removes confusion such as #416

doc: query naming rules

---

lua/nvim-treesitter/textobjects/select.lua

Fixes #418 
The `selection_mode` variable should not be `"n"`, but it's inferring the mode from the current mode which is normal mode.

fix: TSTextobjSelect command

---

queries/typescript/textobjects.scm

`interface`, `type` and `enum` declarations are now supported as class `textobject`s.
Known issues:
- the last semicolon (`;`) of the inner text (`interface`, `type`) or the last comma of the inner text (`enum`) are missed.
- an object [declared with `as const`](https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums) isn't supported (`value: as_expression` ending with `type_identifier`)
_This is related to https://github.com/nvim-treesitter/nvim-treesitter-textobjects/discussions/396_

Update TypeScript textobjects for type definition support

---

lua/nvim-treesitter/textobjects/shared.lua

Fixes #441 
Finding adjacent node deals with treesitter range in the wrong way. Especially, when the end pos and start pos are the same (immediately adjacent).

fix: swap adjacent node wrong range

---

queries/r/textobjects.scm

I missed the super assignments on the initial PR https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/447, this adds queries for them.

Add additional R assignment textobjects

---

lua/nvim-treesitter/textobjects/select.lua

At the moment, when using a direct lua function for the key mappings, the "dot-repeat" action does not trigger as expected. For example, `dap` which will  delete a 3 chars parameter, when repeated with `.`, will simply delete 3 chars again, instead of deleting the parameter the cursor is on.
**edit**: Locally, when I try `dVac` (`ac` is "@conditional.outer") then `.` with the old method, I get stuck in an apparent infinite loop. This behaviour is fixed with the new method. I don't know if it is reproducible or if it's due to my config.

fix(dot-repeat): Use '<cmd>...<cr>' style for mapping to enable proper dot repeat

---

queries/scala/textobjects.scm

According to the [latest](https://github.com/tree-sitter/tree-sitter-scala/commit/2d0e6b8c14236ead27aa86236d2d302fbdf5c24b) treesitter grammar for scala function is defined as:
```
function_definition: $ => seq(
repeat($.annotation),
optional($.modifiers),
'def',
$._function_constructor,
choice(
seq('=', field('body', $._indentable_expression)),
field('body', $.block)
)
)
```
where `_indentable_expression` is:
```
_indentable_expression: $ => choice(
$.indented_block,
$.indented_cases,
$.expression,
)
```

feat: [scala] Update function body node type

---

queries/go/textobjects.scm

Fixes https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/460
Definition `parameter_declaration`: https://github.com/tree-sitter/tree-sitter-go/blob/7cccc30535a40da07092626031120ae6b36202d7/grammar.js#L236

fix(go): update definition of `@parameter`

---

queries/matlab/textobjects.scm

nvim-treesitter/nvim-treesitter#4944 just got accepted, so this adds support for the textobjects for that parser.
btw, didn't you have any textobjects before for matlab? I was under the impression it existed, but now I see it's not here...

fix(matlab): nvim-treesitter changed the parser.

---

lua/nvim-treesitter/textobjects/repeatable_move.lua

This fixes the following error from being thrown when "original" vim repeat keybinds are set and `repeat_last_move_opposite` is called before `repeat_last_move`:
```lua
-- vim way: ; goes to the direction you were moving.
vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat_move.repeat_last_move)
vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat_move.repeat_last_move_opposite)
```
<details>
<summary>Error Message</summary>
```
E5108: Error executing lua: ...ects/lua/nvim-treesitter/textobjects/repeatable_move.lua:114: attempt to index field 'last_move' (a nil value)
stack traceback:
...ects/lua/nvim-treesitter/textobjects/repeatable_move.lua:114: in function <...ects/lua/nvim-treesitter/textobjects/repeatable_move.lua:113>
```
</details>

fix: check if `last_move` exists before repeating opposite move

---

queries/rust/textobjects.scm

`type_identifier` in `parameters` matches with parameters in function pointer types such as each `String` below:
```rust
type foo = fn(String, String) -> ();
```
`_` in `tuple_type` matches with types in tuple such as each `String` below:
```rust
type foo = (String, String);
```

feat(rust): add `@parameter` for type

---

queries/rust/textobjects.scm

Related to https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/2
```rust
#[derive(Debug, Clone)]
struct Test;
```
textobject around `Debug` and `Clone`.

feat(rust): Add `token_tree` to `@parameter.inner`

---

queries/astro/textobjects.scm

Astro's textobjects are the same as HTML's textobjects, so it's just inherited from HTML.
Fixes https://github.com/virchau13/tree-sitter-astro/issues/19.

feat: add astro textobjects

---

queries/c/textobjects.scm
queries/ecma/textobjects.scm

exclude curly braces for c and ts

---

.github/workflows/consistency_tests.yml

For some reason the behaviour in Python changed, but I haven't found any issues so far so I'm updating to match the new version.

test: update consistency tests

---

queries/ecma/textobjects.scm

One thing I've found very useful in the last couple of weeks is adding object keys/values to the `@assignment.lhs`/`@assignment.rhs` textobjects for JavaScript / Typescript.
Here's a preview:
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/543561/a998c126-e2b4-452c-9871-0c9cb8dfb622
Even though it broadens the definition of assignment, it feels very intuitive after you take it for a quick spin.

Add assignment textobjects for JS/TS object keys/values

---

lua/nvim-treesitter/textobjects/select.lua

The value of `config.selection_modes` is only considered when we are in `operation pending mode`. The example below describes the issue that this PR can solve.
1. Set `config.selection_modes["@function.outer"] = "V"`
2. Type `"vaf"` in normal mode.
3. We get pure `"v"` mode enabled instead of `"V"`
In my opinion, we should also consider the value of `config.selection_modes` in the case of `{"v", "V", "<C-v>"}`. Please kindly review the description, and I would really appreciate it if I could get any feedback.
Fixes #515

fix(select.lua): Fix condition for 'visual_mode' selection

---

queries/rust/textobjects.scm

To my understanding, macro invocations should be considered a type of function call. Would also resolve [this issue](https://github.com/kylechui/nvim-surround/issues/290#issuecomment-1854629989).

feat(rust): Add `macro_invocation` as a type of `@call.outer`.

---

queries/ecma/textobjects.scm

Provides appropriate `@call.inner` and `@call.outer` text objects for object constructors, e.g. `new MyObject(5, 'hi')`

feat(ecma): `@call` object for constructor calls

---

queries/lua/textobjects.scm

This PR makes it so that `(comment)` nodes are ignored when recognizing `@parameter.(inner|outer)` textobjects in Lua tables. We now only capture `(field)` nodes. This helps with swapping and deletion, when doing both actions while having comments inbetween fields, currently the behavior is quite buggy because the `(_)` query will capture comments, and improperly since they do not have the associated `","` node. This PR also removes a query to simplify and improve captures, and it is not necessary because tables (unlike the similar parameter and argument queries) *can* have trailing commas, so we don't need to create any finnicky captures. To test, notice the difference when swapping `@parameter.inner` with something like the following:
```lua
local swapme = {
-- comment
'fieldhere', …
```

fix(lua): ignore comments for table inner param

---

queries/latex/textobjects.scm

Gives `@call.(outer|inner)` text objects to LaTeX functions, to closer match the highlights. Extends the objects to text functions, and their inner content.

fix(latex): proper function call text objects

---

queries/toml/textobjects.scm

Includes array elements, key-val pair in inline tables and key-val pairs in normal tables.

feat(toml): Add @parameter.inner and @parameter.outer

---

lua/nvim-treesitter/textobjects/shared.lua
lua/nvim-treesitter/textobjects/swap.lua

Right now the `adjacent` node to be swapped does not have its range metadata preserved properly. This results in weird asymmetrical behavior when swapping nodes that have their own capture ranges, such as the following:
```scheme
((list_item) @swappable
(#trim! @swappable))
```
Currently, such swaps will include a blank new line at the end, but only when swapping from the second to last list item to the last list item (the reverse direction is unaffected; this also only applies when a new line follows the list). This PR fixes that by preserving the range.

fix(swap): preserve swapped nodes' range metadata

---

queries/fennel/textobjects.scm

Updating queries to account for the new parser introduced in nvim-treesitter/nvim-treesitter#6132.

queries/fennel: update queries for the new grammar

---

lua/nvim-treesitter/textobjects/shared.lua

Apologies!! The previous PR caused a nil index error when swapping out of the node ranges (e.g. swapping with a previous node when already at the first node). This should fix it.
Lua is quirky...

fix: nil index when swapping at first/last child

---

queries/css/textobjects.scm

These are the property/value textobjects for CSS.
Selecting property (key): 
Selecting value:
However there's an edge case which I don't know how to properly handle. It has to do with some properties having multiple values. With the current implementation, only one of the values is selected (the closest one).
`background-image`:
`transition`:
As a workaround we can make `@assignment.rhs` and `@assignment.inner` (which seem to be synonyms in most language queries) to differ slightly and have `@assignment.rhs` capture all the values and `@assignment.inner` capture one value only.
Having the following keymaps works very intuitively for this setup:
``` lua
['ik'] = '@assignment.lhs', -- select the key
['ak'] = '@assignment.outer', -- select the whole assignment
['iv'] = '@assignment.inner', …
```

Add assignment textobjects to CSS

---

queries/c/textobjects.scm

Allows `@conditional.inner` to include not just the body of e.g. an if statement, but also the condition itself (and conditions for while loops, do while, etc.)

feat(c): add text objects for statement conditions

---

queries/c/textobjects.scm

Problem : #585 
Solution : 
- Assignment inner/outer/left/right now fully works on declaration such as `int a = 3` and definitions such as `int a = 10`
- It does also work on expression_statement such as `a = 0` (notice there is no type here)

feat(c): assignment operator for c

---

queries/rust/textobjects.scm

Adds support for the `self` param.

rust: add self_parameter query

---

queries/haskell/textobjects.scm

The parser had a rewrite giving lots of invalid nodes. This fixes all the errors (but maybe too lazily in some cases? not 100% confident about these changes so hopefully someone can confirm they are valid)

fix(haskell): update queries for new parser

---

queries/c_sharp/textobjects.scm

It appears that `for_each_statement` was renamed to `foreach_statement`, which was causing neovim to throw errors.
https://github.com/tree-sitter/tree-sitter-c-sharp/commit/afe8bb1932b8d73cd23b9c8d8fdf668166212d47
https://github.com/nvim-treesitter/nvim-treesitter/commit/6587d8e6942b8d2146d61bab4c4acff9dec5ae59
This change fixed it for me :).

fix(c_sharp):  Rename for_each_statement to foreach_statement

---

lua/nvim-treesitter/textobjects/lsp_interop.lua

See: https://neovim.io/doc/user/deprecated.html#deprecated-0.10
`Deprecated vim.tbl_islist() Use vim.islist() instead.`

Added islist compatibility function for Neovim 0.12+

---

.github/workflows/lint.yml
scripts/ci-install-ubuntu-latest.sh

Adapts the linter to use the query parser in the nvim-treesitter repo, rather than the bundled Neovim one. This prevents breaking parser changes from messing up the formatting lint.
See https://github.com/nvim-treesitter/nvim-treesitter/commit/d3acd105bd48b6529cb5dc02e73d96990862e196

ci(lint): use query parser from nvim-treesitter

---

README.md
lua/nvim-treesitter/textobjects/repeatable_move.lua
scripts/minimal_init.lua

fixes #519 
The current implementation of builtin `f`, `F`, `t`, `T` is a re-implementation to match the behaviour of the nvim upstream. Although it works with `;` and `,` movement repeat, unfortunately it probably wouldn't work with complex combinations (e.g. `dfe` and `.` repeat wouldn't work).
Instead, we can make `builtin_f_expr`, `builtin_F_expr`, ... just returns `"f"`, `"F"`, `"t"`, `"T"` character so you can use it to map with `{expr = true}`. See the implementation below. This will almost likely resemble the upstream behaviour in most of the situations.
```lua
M.builtin_f_expr = function()
M.last_move = {
func = "f",
opts = { forward = true },
additional_args = {},
}
return "f"
end
```
Before returning the string, note that it also maps the last movement so the `;` and `,` …

fix: builtin find not working with dot repeat

---

queries/odin/textobjects.scm

Treesitter predicate changed upstream to align with Helix: https://github.com/nvim-treesitter/nvim-treesitter/commit/a80fe081b4c5890980561e0de2458f64aaffbfc7

fix(odin): update `has-type` renamed to `kind-eq`

---

queries/r/textobjects.scm

The R grammar (https://github.com/r-lib/tree-sitter-r) was recently rewrote, which introduced breaking changes in `nvim-treesitter`. See https://github.com/nvim-treesitter/nvim-treesitter/commit/5373c90c55a33408604d17713edaa9560306b83d.
These breaking changes were addressed in these two commits:
1. https://github.com/nvim-treesitter/nvim-treesitter/commit/3e535e826da265748b875b18dbfb361bd1a1701c
2. https://github.com/nvim-treesitter/nvim-treesitter/commit/f0e3b5c5fe38d0012c63368db90017fef87c85a2
However, the changes in `tree-sitter-r` also broke `nvim-treesitter-textobjets` because node names were change (https://github.com/nvim-treesitter/nvim-treesitter/issues/6849):
```
Error detected while processing BufNewFile Autocommands for "*": …
```

Update to support the complete re-writing of the R parser

---

queries/elixir/textobjects.scm

Add functions with `when` guard clauses and functions without parameters with and without guard clauses
Fixes #640

fix(elixir): add functions with guard clauses and/or no params

---

plugin/query_predicates.lua

This PR attempts to fix the following error when using text objects in R source file. The following is an example of R file:
```r
hello <- function()
|print('hello')
}
```
Where `|` is the cursor position.
The following is an example of nvim config
```lua
vim.keymap.set({ 'x', 'o' }, 'af', function()
require('nvim-treesitter-textobjects.select').select_textobject('@function.outer', 'textobjects')
end)
```
pressing `af` at the cursor position will lead to the following error:
```lua
E5108: Error executing lua: .../nvim-treesitter-textobjects/plugin/query_predicates.lua:13: attempt to get length of local 'start_nodes' (a nil value)          
stack traceback: …
```

fix: handle nil start_nodes for `query_predicates`.

---

queries/python/textobjects.scm

This PR adds augmented assignments to python so that expressions like
`x += y`
are captured as well.

Python: augmented assignments

---

lua/nvim-treesitter-textobjects/select.lua
lua/nvim-treesitter-textobjects/shared.lua

Two bugs in the code cause the select feature to be totally unusable after `include_surrouding_whitespaces` is enabled.

fix: include_surrouding_whitespaces

---

README.md

`include_surrounding_whitespace` should be inside the `select`.

docs: fix the position of the `include_surrounding_whitespace`

---

lua/nvim-treesitter-textobjects/move.lua

This line tries to access `range` on `TSTextObjects.Range`, which does not have this field, so the passed value will be `nil`. This bug makes the `move` feature usable.

fix: avoid pass nonexistent field

---

lua/nvim-treesitter-textobjects/move.lua
lua/nvim-treesitter-textobjects/repeatable_move.lua
lua/nvim-treesitter-textobjects/select.lua
lua/nvim-treesitter-textobjects/shared.lua

The first two are easy to understand, for the third one, LuaLS could not match a return type of `integer, integer, integer, integer` to `{ [1]: integer, [2]: integer, [3]: integer, [4], integer }` when it was packed. Obviously, the original author noticed that so they provided `unpack4` for that. This makes the code more consistent and removes the wrong diagnostic error.

Some fixes for types

---

lua/nvim-treesitter-textobjects/swap.lua

The actual way to use it is `require("nvim-treesitter-textobjects.swap").swap_next("@parameter.inner")()`, not as the [what the readme said](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/tree/main#text-objects-swap). The closure is unnecessary.

fix: avoid unnecessary closures

---

queries/latex/textobjects.scm

This PR fixes and improves LaTeX block and frame queries:
- arbitrary length blocks/frames are supported
- `@frame` works now
- `@class.inner` supported

feat(latex): improved block/frame and sections

---

README.md
lua/nvim-treesitter-textobjects/move.lua
lua/nvim-treesitter-textobjects/repeatable_move.lua

Also stop advertising as generic API and point to nvim-next instead.

fix(repeatable_move): remove deprecated and unused functions

---

queries/zig/textobjects.scm

fix(zig): exclude braces in function.inner

---

queries/php/textobjects.scm

- Renamed `anonymous_function_creation_expression` to `anonymous_function` to align with the upstream change in tree-sitter-php (see tree-sitter/tree-sitter-php#247).

fix(php): Update syntax for anonymous functions

---

lua/nvim-treesitter-textobjects/move.lua
lua/nvim-treesitter-textobjects/repeatable_move.lua
lua/nvim-treesitter-textobjects/swap.lua

`repeatable_move` is out of the plugin's scope, and I agree with simplifying it. But even if the `make_repeatable_move_pair` was removed, the current API is good enough for users to define their repeatable move, it only needs some refactoring and documentation. Also contains some tiny improvements for type annotations.
`nvim-next` does not support the `main` branch, so there's no replacement for users now, but since its author knows this so it might be implemented in the future, so I kept the reference to `nvim-next`. see https://github.com/ghostbuster91/nvim-next/issues/22.
Edit:
I changed this PR to `feat` because the `MoveFunction` interface should be guaranteed.

refactor(repeatable_move): extract the `MoveFunction` interface

---

queries/apex/textobjects.scm
queries/ecma/textobjects.scm
queries/go/textobjects.scm
queries/julia/textobjects.scm
queries/lua/textobjects.scm

Goal of PR (For all languages which support either of the first 1-4 text objects): 
- Change `assignment.outer` so that it captures extra tokens like `const` and semicolon
```ts
const x = 5;
```
- `@assignment.outer`: `const x = 5;`
```c
int x = 5;
```
- `@assignment.outer`: `int x = 5;`
```bash
x=5
```
- `@assignment.outer`: `x=5`
```python
x = 5
```
- `@assignment.outer`: `x=5`
```css
body {
margin: 1px 2px 3px 4px;
}
```
- `@assignment.outer`: `margin: 1px 2px 3px 4px;`
a -> b, c means b and c inherit from a, so no changes were made to b or c
Closes #681

feat: modify behaviour of `@assignment.outer` so it includes keywords like `const`, `local` etc. and semicolon

---

queries/lua/textobjects.scm

Now includes the preceding comma for the final field of a table.

fix(lua): better @parameter.outer capture for fields

---

queries/julia/textobjects.scm

This is introduced by [aad2c8e6b029](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/aad2c8e6b029ada30621e67780801420ee9debe9).

fix(julia): query syntax error

---

README.md
lua/nvim-treesitter-textobjects/repeatable_move.lua
scripts/minimal_init.lua
tests/select/python_spec.lua

https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/699

fix(repeatable_move)!: make `d;` work like the builtin behavior

---

queries/julia/textobjects.scm

This patch adapts the julia queries to the breaking changes in
https://github.com/tree-sitter/tree-sitter-julia/pull/153.
fixes #716

fix(julia): adapt queries to parser changes

---

lua/nvim-treesitter-textobjects/select.lua

Fixes #488
When the user has `set selection=exclusive` the selection was one character short. This PR addresses that.
Note that this PR fixes it in the `main` branch. The `master` branch uses a function [outside of this repo](https://github.com/afgomez/nvim-treesitter-textobjects/blob/bf8d2ad35d1d1a687eae6c065c3d524f7ab61b23/lua/nvim-treesitter/textobjects/select.lua#L114), so it cannot be fixed here.

fix: Adjust selected range when `set selection=exclusive`

---

lua/nvim-treesitter/textobjects/lsp_interop.lua

Adapt to the upstream change https://github.com/neovim/neovim/commit/629483e24eed3f2c07e55e0540c553361e0345a2 to get rid of the warning message "warning: offset_encoding is required, using the offset_encoding from the first client".
Since the commit https://github.com/neovim/neovim/commit/2dcbfe78fcec5f73ce061bb24b718187b9c6b134, `params` in `buf_request` can accept a function that takes the client as a parameter. So instead of sending the same params to all servers, the params with correct offset_encoding will send to each single server.

fix: offset_encoding is required now in `make_position_params`

---

queries/ecma/textobjects.scm

Added lexical declarations to @statement.outer capture group, e.g:
```
const a = 1;
```
should be selectable using @statement.outer capture group.

Update @statement.outer query for Ecma to also include lexical declarations

---

queries/ocaml/textobjects.scm

I'm a treesitter queries newbie, so I'd appreciate the feedback on these queries.
This is an example of syntactically correct ocaml I used to test them:
```ocaml
let example_function param1 param2 = param1 + param2
class example_object =
object (self)
method do_stuff x = raise Not_found
end
(* This is a comment. *)
let some_loops () =
for variable = start_value to end_value do
expression
done;
while boolean - condition do
expression
done
let conditionals () =
let if_condition = if a then b else c in
let match_cases = match a with b -> 1 | c -> 2 in
let function_expression = function b -> 1 | c -> 2 in
()
let test_call =
(* A function call, followed by 3 arguments. *)
String.fold (fun a b -> a) 0 xs
let some_blocks =
let begin_block = begin
let inner_block = a in
b
end
in
let paren_block = …
```

feat(ocaml): Add OCaml queries

---

lua/nvim-treesitter/textobjects/lsp_interop.lua

This PR solves a bug introduced in 4fc5b1e for nvim-0.11.
`make_position_params()` is in `vim.lsp.util`, not in `vim.api.util`.

fix(typo): `vim.api.util` to `vim.lsp.util`

---

queries/kotlin/textobjects.scm

In Kotlin classes, the body is optional, but the `@class` text objects were failing to capture classes without a body.
This change makes `@class.outer` work for those cases, but `@class.inner` is ignored since these classes does not have an "inner"

fix (kotlin): capture `@class.outer` on classes without a body

---

queries/jsx/textobjects.scm

In React, it was using `@parameter.*` queries when there was already a more appropriate one called `@attribute`.
I also made it analogous to the HTML's selection by selecting the inner part of the string/variable with `@attribute.inner`.
Before: `@parameter.inner`
```jsx
<Button variant="text">This is a button</Button>
//              ╰────╯
```
After: `@attribute.inner`
```jsx
<Button variant="text">This is a button</Button>
//               ╰──╯
```

fix(jsx): use `@attribute.*` over `@parameter.*`

---

queries/ecma/textobjects.scm

Replace basic node capture for class.inner with make-range! implementation to select class body content without including braces. This makes class.inner behavior consistent with function.inner, providing a more intuitive text object selection for editing class contents.

feat(ecma): refine class.inner text object selection

---

queries/ecma/textobjects.scm

Following the discussion in #86 
Removed `formal_parameters -> array_pattern` etc. because now all kinds of array_pattern and object_pattern are matched.

feat(ecma): array pattern, object pattern as `@parameter`

---

queries/rust/textobjects.scm

Links #86 
Also part of #766 for Rust.

feat(rust): `array_expression` as `@parameter`

---

queries/typescript/textobjects.scm

Addresses https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/86#issuecomment-2970072351

feat(typescript): `type` and `interface` as `@parameter.*`

---

README.md
lua/nvim-treesitter-textobjects/repeatable_move.lua
scripts/minimal_init.lua

Should fix https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/775
https://github.com/user-attachments/assets/afecce63-6db3-42c8-977b-e1a209ae9c68
Not sure if this fix is already being addressed in another way or refactor process, but just in case, the move_repeatable function was failing when no string was being returned (nil in this case) due to { expr = true } keymap options.

fix(repeatable_move): bug when nil was returned or normal command used; no longer requires { expr = true }
